# Generated by Django 5.0.3 on 2024-03-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='diagnostic/')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['type'],
                'indexes': [models.Index(fields=['type'], name='diagnostic__type_1f5bf1_idx')],
            },
        ),
    ]
