# Generated by Django 5.0.3 on 2024-03-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='image',
            field=models.ImageField(upload_to='check_you_smile/diagnostic/diagnostic/'),
        ),
    ]
