# Generated by Django 5.0.3 on 2024-03-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_alter_diagnostic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
