# Generated by Django 5.0.3 on 2024-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_alter_diagnostic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='image',
            field=models.ImageField(upload_to='diagnostic_img/'),
        ),
    ]
