# Generated by Django 5.0.3 on 2024-03-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_alter_diagnostic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
