# Generated by Django 5.0.3 on 2024-03-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0006_diagnostic_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='url',
            new_name='name',
        ),
    ]
