# Generated by Django 5.0.3 on 2024-03-28 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0007_rename_url_diagnostic_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PhotoDiagnostic',
            fields=[
                ('alldiagnostic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diagnostic.alldiagnostic')),
                ('type', models.CharField(default='pho', max_length=20)),
                ('result_diagnostic', models.JSONField(blank=True)),
            ],
            bases=('diagnostic.alldiagnostic',),
        ),
        migrations.AddIndex(
            model_name='alldiagnostic',
            index=models.Index(fields=['date'], name='diagnostic__date_5251c9_idx'),
        ),
    ]
