# Generated by Django 5.0.3 on 2024-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0008_alldiagnostic_photodiagnostic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldiagnostic',
            name='slug',
            field=models.SlugField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='photodiagnostic',
            name='image_frontal',
            field=models.ImageField(default=None, upload_to='user_img/<django.db.models.query_utils.DeferredAttribute object at 0x7f237c5b84d0>/'),
        ),
        migrations.AddField(
            model_name='photodiagnostic',
            name='image_lateral',
            field=models.ImageField(default=None, upload_to='user_img/<django.db.models.query_utils.DeferredAttribute object at 0x7f237c5b84d0>/'),
        ),
    ]
