# Generated by Django 5.0.3 on 2024-03-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0009_alldiagnostic_slug_photodiagnostic_image_frontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodiagnostic',
            name='image_frontal',
            field=models.ImageField(default=None, upload_to='user_img/<django.db.models.query_utils.DeferredAttribute object at 0x79391bf34890>/'),
        ),
        migrations.AlterField(
            model_name='photodiagnostic',
            name='image_lateral',
            field=models.ImageField(default=None, upload_to='user_img/<django.db.models.query_utils.DeferredAttribute object at 0x79391bf34890>/'),
        ),
        migrations.AlterField(
            model_name='photodiagnostic',
            name='result_diagnostic',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
