# Generated by Django 5.0.3 on 2024-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0011_alter_photodiagnostic_image_frontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodiagnostic',
            name='image_frontal',
            field=models.ImageField(default=None, upload_to='user_img/'),
        ),
        migrations.AlterField(
            model_name='photodiagnostic',
            name='image_lateral',
            field=models.ImageField(default=None, upload_to='user_img/'),
        ),
    ]
