# Generated by Django 5.0.3 on 2024-03-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0013_remove_alldiagnostic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodiagnostic',
            name='image_frontal',
            field=models.ImageField(default=None, upload_to='user_img/%Y.%m.%d.%H.%M'),
        ),
        migrations.AlterField(
            model_name='photodiagnostic',
            name='image_lateral',
            field=models.ImageField(default=None, upload_to='user_img/%Y.%m.%d.%H.%M'),
        ),
    ]
