# Generated by Django 5.0.3 on 2024-04-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0017_remove_photodiagnostic_result_diagnostic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photodiagnostic',
            name='id_task_diagnostic',
        ),
        migrations.AddField(
            model_name='photodiagnostic',
            name='result_diagnostic',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
